//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class liketable
    {
        public int id { get; set; }
        public string backgroundColor { get; set; }
        public string lettersColor { get; set; }
        public Nullable<bool> enjoyed { get; set; }
        public string customer_location { get; set; }
        public Nullable<System.DateTime> customer_date { get; set; }
    }
}
